apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "varmor.agent.fullname" . }}
  namespace: {{ include "varmor.namespace" . }}
  labels:
    {{- include "varmor.agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "varmor.agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "varmor.agent.selectorLabels" . | nindent 8 }}
      annotations:
        {{- with .Values.agent.podAnnotations }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if semverCompare "<1.30.0-0" .Capabilities.KubeVersion.Version }}
        container.apparmor.security.beta.kubernetes.io/agent: unconfined
        {{- end }}
    spec:
      {{- if .Values.image.password }}
      imagePullSecrets:
        {{- with .Values.imagePullSecrets }}
          {{- toYaml . | nindent 6 }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ include "varmor.agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.agent.podSecurityContext | nindent 8 }}
      hostPID: true
      {{- if .Values.agent.network.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end}}
      containers:
      - name: {{ .Values.agent.name }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.namespace }}/{{ .Values.agent.image.name }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
        command: ["/varmor/vArmor", "--agent"]
        {{- if or .Values.jsonLogFormat.enabled .Values.agent.args .Values.behaviorModeling.enabled .Values.bpfLsmEnforcer.enabled .Values.unloadAllAaProfiles.enabled .Values.removeAllSeccompProfiles.enabled }}
        args:
          {{- if .Values.jsonLogFormat.enabled }}
            {{- with .Values.jsonLogFormat.args }}
              {{- toYaml . | nindent 8 }}
            {{- end }}
          {{- end }}
          {{- if .Values.agent.args }}
            {{- with .Values.agent.args }}
              {{- toYaml . | nindent 8 }}
            {{- end }}
          {{- end }}
          {{- if .Values.behaviorModeling.enabled }}
            {{- with .Values.agent.behaviorModeling.args }}
              {{- toYaml . | nindent 8 }}
            {{- end }}
          {{- end }}
          {{- if .Values.bpfLsmEnforcer.enabled }}
            {{- with .Values.agent.bpfLsmEnforcer.args }}
              {{- toYaml . | nindent 8 }}
            {{- end }}
          {{- end }}
          {{- if .Values.unloadAllAaProfiles.enabled }}
            {{- with .Values.agent.unloadAllAaProfiles.args }}
              {{- toYaml . | nindent 8 }}
            {{- end }}
          {{- end }}
          {{- if .Values.removeAllSeccompProfiles.enabled }}
            {{- with .Values.agent.removeAllSeccompProfiles.args }}
              {{- toYaml . | nindent 8 }}
            {{- end }}
          {{- end }}
        {{- end }}
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: READINESS_PORT
          value: "{{ .Values.agent.network.readinessPort }}"
        {{- if .Values.auditEventMetadata }}
        - name: AUDIT_EVENT_METADATA
          value: '{{- toJson .Values.auditEventMetadata}}'
        {{- end }}
        securityContext:
          {{- with .Values.agent.securityContext }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if semverCompare ">=1.30.0-0" .Capabilities.KubeVersion.Version }}
          appArmorProfile:
            type: Unconfined
          {{- end }}
        volumeMounts:
        - mountPath: /sys/kernel/security
          name: securityfs
        - mountPath: /var/lib/kubelet/seccomp
          name: seccomp-dir
        - mountPath: /run/containerd
          name: containerd
        - mountPath: /var/log
          name: var-log-dir
        - mountPath: /var/run/secrets/tokens
          name: bound-token
        {{- if .Values.appArmorLsmEnforcer.enabled }}
          {{- with .Values.agent.appArmorLsmEnforcer.volumeMounts }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
        {{- end }}
        {{- if or .Values.bpfLsmEnforcer.enabled .Values.behaviorModeling.enabled }}
          {{- with .Values.agent.bpfRelated.volumeMounts }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
        {{- end }}
        {{- if .Values.behaviorModeling.enabled }}
          {{- with .Values.agent.behaviorModeling.volumeMounts }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
        {{- end }}
        resources:
        {{- if .Values.behaviorModeling.enabled }}
          {{- toYaml .Values.agent.behaviorModeling.resources | nindent 10 }}
        {{- else if .Values.bpfLsmEnforcer.enabled }}
          {{- toYaml .Values.agent.bpfLsmEnforcer.resources | nindent 10 }}
        {{- else }}
          {{- toYaml .Values.agent.appArmorLsmEnforcer.resources | nindent 10 }}
        {{- end }}
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: {{ .Values.agent.network.readinessPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - hostPath:
          path: /sys/kernel/security
          type: Directory
        name: securityfs
      - hostPath:
          path: /var/lib/kubelet/seccomp
          type: DirectoryOrCreate
        name: seccomp-dir
      - hostPath:
          path: /run/containerd
          type: Directory
        name: containerd
      - hostPath:
          path: /var/log
          type: Directory
        name: var-log-dir
      - projected:
          sources:
          - serviceAccountToken:
              path: bound-token
              expirationSeconds: 7200
              audience: varmor-manager
        name: bound-token
      {{- if .Values.appArmorLsmEnforcer.enabled }}
        {{- with .Values.agent.appArmorLsmEnforcer.volumes }}
          {{- toYaml . | nindent 6 }}
        {{- end }}
      {{- end }}
      {{- if or .Values.bpfLsmEnforcer.enabled .Values.behaviorModeling.enabled }}
        {{- with .Values.agent.bpfRelated.volumes }}
          {{- toYaml . | nindent 6 }}
        {{- end }}
      {{- end }}
      {{- if .Values.behaviorModeling.enabled }}
        {{- with .Values.agent.behaviorModeling.volumes }}
          {{- toYaml . | nindent 6 }}
        {{- end }}
      {{- end }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
