apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: varmor-manager
  labels:
    app: varmor
rules:
# controller
- apiGroups:
  - crd.varmor.org
  resources:
  - armorprofiles
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - crd.varmor.org
  resources:
  - armorprofiles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.varmor.org
  resources:
  - varmorpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.varmor.org
  resources:
  - varmorpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crd.varmor.org
  resources:
  - varmorclusterpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.varmor.org
  resources:
  - varmorclusterpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - update
- apiGroups:
  - crd.varmor.org
  resources:
  - armorprofilemodels
  verbs:
  - get
  - create
  - update
- apiGroups:
  - crd.varmor.org
  resources:
  - armorprofilemodels/status
  verbs:
  - get
  - patch
  - update
# webhook
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - delete
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create