{{- if .Values.behaviorModeling.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: varmor-classifier-svc
  namespace: {{ include "varmor.namespace" . }}
  labels:
    {{- include "varmor.classifier.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 5000
    name: class
    targetPort: {{ .Values.classifier.network.servicePort }}
  selector:
     {{- include "varmor.classifier.selectorLabels" . | nindent 4 }}
{{- end}}
