apiVersion: v1
kind: Service
metadata:
  name: varmor-webhook-svc
  namespace: {{ include "varmor.namespace" . }}
  labels:
    {{- include "varmor.manager.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 443
    name: status
    targetPort: {{ .Values.manager.network.webhookPort }}
  selector:
    {{- include "varmor.manager.selectorLabels" . | nindent 4 }}
