name: ci-alpha-basic-test

on:
  workflow_run:
    workflows: ["ci-alpha-build"]
    types:
      - completed


jobs:
  deploy-and-basic-test:
    strategy:
      fail-fast: false
      matrix:
        k8s_version: [ "1.23", "1.24", "1.26" ]
        os: [ "ubuntu-22.04-bpf", "debian-11-bpf" ]
    runs-on: ${{ matrix.os }}
    env:
      KUBE_VER: ${{ matrix.k8s_version }}
    steps:
      - name: Create a K3s cluster
        run: ./.github/scripts/create-k3s-cluster.sh
      - name: Install varmor alpha version
        run: |
          helm install varmor "$GIT_VERSION".tgz \
              --namespace varmor --create-namespace \
              --set image.registry="elkeid-test-cn-beijing.cr.volces.com" \
              --set image.username=${{ secrets.TEST_USERNAME }}" \
              --set image.password=${{ secrets.TEST_PASSWORD }}" \
              --set bpfLsmEnforcer.enabled=true
      - name: Run basic test
        run: ./.github/scripts/basic-test.sh
      - name: Kill all and clean up
        if: ${{ always() }}
        run : ./.github/scripts/kill-and-clean-all.sh