name: alpha-build
on:
  pull_request:
    branches:
      - main
    paths:
      - "apis/**"
      - "cmd/**"
      - "config/**"
      - "internal/**"
      - "pkg/**"
      - ".gitmodules"
      - "manifests/**"
      - "vArmor-ebpf/**" # check submodule content

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8

      - name: Set up llvm and apparmor
        run: ./.github/scripts/toolchain.sh

      - name: Build dev image
        run: make docker-build-dev

      - name: Login to Docker Hub
        run: echo "${{ secrets.PUSH_PASSWORD }}"|docker login -u=${{ secrets.PUSH_USERNAME }} elkeid-test-cn-beijing.cr.volces.com --password-stdin

      - name: Package helm chart
        run: make helm-package-dev

      - name: Push image to registry
        run: make push-dev
