name: ci-bightly-build
on:
  pull_request:
    types:
      - labeled
  push:
    branches:
      - main
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.SetVersion.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8

      - name: Run build
        run: make docker-build-dev

      - name: Package helm chart
        run: make helm-package-dev

      - name: Login to registry
        run: echo "${{ secrets.PUSH_PASSWORD }}" | docker login -u=${{ secrets.PUSH_USERNAME }} elkeid-ap-southeast-1.cr.volces.com --password-stdin

      - name: Push artifacts to registry
        run: make push-dev